include:
  - clients.yml
  - servers.yml
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  load-balancer:
    build: ./load-balancer
    depends_on:
      server-01:
        condition: service_healthy
      server-02:
        condition: service_healthy
      server-03:
        condition: service_healthy
    environment:
      RPYC_SERVERS: |
        server-01:18861
        server-02:18861
        server-03:18861
    ports:
      - 18861:18861

  # Interactive client to attach to
  client-interactive:
    build:
      context: ./client
      additional_contexts:
        common: ./common
    environment:
      RPYC_HOST: "load-balancer"
      RPYC_PORT: "18861"
    entrypoint: ["sleep", "infinity"]
