services:
  redis:
    image: redis:7-alpine
    container_name: wc-redis
    ports:
      - "6379:6379"

  server:
    container_name: wc-server
    build:
      context: ./server
      dockerfile: ../adsimg.Dockerfile
    volumes:
      - ./server/data:/data
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_TTL_SECONDS: "86400" # cache for 1 day
      RPYC_PORT: "18861"
      DOCS_DIR: "/data"
    depends_on:
      - redis
    ports:
      - "18861:18861"
    entrypoint: ["python", "-u", "main.py"]
  # Client is optional as a long-running service; we run it on-demand.
  client:
    container_name: wc-client
    build:
      context: ./client
      dockerfile: ../adsimg.Dockerfile
    depends_on:
      - server
    entrypoint: ["python", "-u", "main.py", "--mock"]
