services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: ./server
      additional_contexts:
        common: ./common
    volumes:
      - ./server/data:/data:ro
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_TTL_SECONDS: "86400" # cache for 1 day
      RPYC_PORT: "18861"
      DOCS_DIR: "/data"
    depends_on:
      - redis
    ports:
      - "18861:18861"
  # Mock client to create artificial server load
  client-mock:
    build:
      context: ./client
      additional_contexts:
        common: ./common
    depends_on:
      server:
        condition: service_healthy
    environment:
      RPYC_HOST: "server"
      RPYC_PORT: "18861"

  # Interactive client to attach to
  client-interactive:
    build:
      context: ./client
      additional_contexts:
        common: ./common
    depends_on:
      - server
    environment:
      RPYC_HOST: "server-1"
      RPYC_PORT: "18861"
    entrypoint: ["sleep", "infinity"]
